name: fs2jobbuild

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [2.12.10, 2.13.1]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Git Actor
        run: git config github.actor slamdata-bot
      - name: Compile and test
        run: ./sbt -DisIsolatedEnv=${ISOLATED_ENV:=false} ++${{ matrix.scala }} checkHeaders test:compile test "testOnly -- failtrace"
      - name: Upload target
        uses: actions/upload-artifact@v1
        with:
          name: target-${{ matrix.scala }}
          path: target

  publishandtag:
    name: Publish and Tag
    needs: [build]
    if: github.event_name != 'pull_request' && (contains(github.head_ref, 'backport/v.*') || contains(github.head_ref, 'master'))
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Download target artifacts
        uses: actions/download-artifact@v1
        with:
          name: target
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Git Actor
        run: git config github.actor slamdata-bot
      - name: Run transferPublishAndTagResources
        run: ./sbt transferPublishAndTagResources
      - name: Run tectonicPublishAndTag
        run: ./scripts/publishAndTag 'slamdata/fs2-job'

  commonResources:
    name: Auto Merge
    if: github.event_name == 'pull_request' && contains(github.head_ref, 'version-bump')
    needs: [build]
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Download target artifacts
        uses: actions/download-artifact@v1
        with:
          name: target
      - name: Setup Git Actor
        run: git config github.actor slamdata-bot
      - name: Install common resources
        run: ./sbt transferCommonResources
      - name: Install ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Common setup
        run: ./scripts/core/commonSetup
      - name: Set env vars
        run: |
          echo ::set-env name=VERSIONS::$(git diff HEAD^1 | grep -e '^[-+][0-9]' | sed 's/^[+\-]//' | sed 's/\.[0-9]*$//' | uniq | wc -l)
          echo ::set-env name=CLONE_DIR::$(mktemp -d "/tmp/slamdata-bump.XXXXXXXX")
          echo ::set-env name=IS_REVISION_LABEL::${{ contains(github.event.pull_request.labels.*.name, 'revision') }}
          echo ::set-env name=REPO_SLUG::${{ github.repository }}
          echo ::set-env name=PR_NUMBER::$(echo "$GITHUB_REF" | cut -d'/' -f3)
      - name: Check auto merge
        run: ./scripts/core/checkAndAutoMerge
